name: Secure CI/CD for PHP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run PHP Lint
        run: php -l index.php

  sast-scan:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/php"

  dependency-scan:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Composer Audit (SCA)
        run: composer audit --no-interaction --format=json

  dast-scan:
    runs-on: ubuntu-latest
    needs: [sast-scan, dependency-scan]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start PHP server
        run: php -S localhost:8000 -t . &

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:8000/index.php"

  deploy:
    runs-on: ubuntu-latest
    needs: [dast-scan]
    if: success()

    steps:
      - name: Deploy to Production
        run: echo "🚀 Deploying PHP App..."
        # Replace with actual deployment command
